#!/usr/bin/python
import sys
#import random
from socket import *
#import socket

def Simple_ftp_server():
    serverPort = 7735
    serverFileName = sys.argv[1]
    print(serverFileName)
    serverSocket = socket(AF_INET, SOCK_DGRAM)
    serverSocket.bind(('', serverPort))
    print("Server up")
    while 1:
        #rand = random.randint(0, 10)#know its use, then may remove
        message, address = serverSocket.recvfrom(1024)#its a window size
        print(message, address)
        
        serverSocket.sendto(message,address)
        
def main():
	Simple_ftp_server()

#program execution starts here	
if __name__ == "__main__":
	main()
	
